env: productdev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8088
spring:
  application:
    name: product
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql:///pm110?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
